apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: didiyudha-com-tls
spec:
  secretName: didiyudha-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: didiyudha.com
  dnsNames:
    - didiyudha.com
    - www.didiyudha.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - didiyudha.com
          - www.didiyudha.com
